# -*-python-*-

from SCons.Errors import EnvironmentError

Import("env")

cppenv = env.Clone(tools = ['cpp'])

cppenv.AppendUnique(CPPDEFINES = ['LIBSTATISKIT_LINALG'])

exclude = """
""".split()

sources = [source for source in cppenv.Glob('*.*') if not source.name in exclude]

targets = cppenv.CppLibrary("statiskit_linalg", sources)
Alias("cpp", targets)
Alias("autowig", targets)
Alias("install", targets)

try:
    wigenv = cppenv.Clone(tools = ['wig'])

    targets = wigenv.BoostPythonWIG('statiskit_linalg', [target for target in targets if target.name.endswith('.h')],
                                    module='../py/_linalg.cpp',
                                    decorator='../py/statiskit/linalg/_linalg.py',
                                    parser_bootstrap=1,
                                    controller='AutoWIG.py',
                                    generator='AutoWIG.py')
    Alias("autowig", targets)
    Alias("install", targets)
except EnvironmentError:
    pass
except Exception:
    raise